---
title: "Project 4"
author: "Jieran Sun"
date: '2023-03-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages({
  library(ggplot2)
})
```

# Question 11

## a) Load R file
```{r source function file}
source("code/profileHMM.R", echo = FALSE)
```

## b) Load data

```{r load data using function}
GBinPr <- parseAlignment("data/GTP_binding_proteins.txt")
ATPase <- parseAlignment("data/ATPases.txt")
```

## c) Learn profile HMM 

```{r Learning profile HMM for the two data}
GBinPrHMM <- learnHMM(GBinPr)
ATPaseHMM <- learnHMM(ATPase)
```

## d) HMM match and insertion analysis

```{r function and plots}
plotMaxFreq <- function(HMMObject, emSlot) {
  EmMat <- as.data.frame(HMMObject[emSlot])
  MaxInd <- which.max(apply(EmMat, 2, max))
  
  plotDF <- data.frame(freq = EmMat[,MaxInd], 
                       symbol = rownames(EmMat))
  ggplot(plotDF, aes(x = symbol, y = freq)) + 
    geom_bar(stat="identity", color="blue", fill="white") 
}

plotMaxFreq(HMMObject = GBinPrHMM, emSlot = "iE") + ylab("Insertion probability") + ggtitle("GTP-binding Protein")
plotMaxFreq(HMMObject = GBinPrHMM, emSlot = "mE") + ylab("Match probability") + ggtitle("GTP-binding Protein")

plotMaxFreq(HMMObject = ATPaseHMM, emSlot = "iE") + ylab("Insertion probability") + ggtitle("ATPase Protein")
plotMaxFreq(HMMObject = ATPaseHMM, emSlot = "mE") + ylab("Match probability") + ggtitle("ATPase Protein")
```

## e) Load unknown dataset

```{r load unknown dataset}
UnknowPr <- parseProteins("data/Unclassified_proteins.txt")
```

## f) Decide protein classes 

```{r return the protein log odds}
OddList <- unlist(lapply(UnknowPr, function(protein){
  OddGTP <- forward(HMM = GBinPrHMM, seq = protein)
  OddATP <- forward(HMM = ATPaseHMM, seq = protein)
  return(OddGTP - OddATP)
}))
```

```{r plot the protein log odds}
plot(OddList, xlab = "Protein index", ylab = "log odd GTP-binding over ATPase")
```
With the plot shown above, we can tell clearly the protein classifications for all unknown protein as they are all separable. 
